version: "3.3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - ./config/plex/config:/config
      - /media/apozel/hardDisk2/Movies:/data/movies
      - /media/apozel/hardDisk3/FILMS:/data/movies2
      - /media/apozel/hardDisk1/Shows:/data/tvshows
      - /home/apozel/Musique:/data/music
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5354:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: always
    environment:
      - VERSION=latest
      - TZ=Europe/Paris
      - ADVERTISE_IP=http://192.168.1.103:32400/
      - PLEX_CLAIM=claim-eYHgfK2TBEzn7H9x5fmt
      - PLEX_UID=1000
      - PLEX_GID=1000

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - qbittorrent
    volumes:
      - ./config/sonarr/config:/config
      - ./config/qbittorrent/downloads:/downloads
      - /media/apozel/hardDisk1/Shows:/tv
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - qbittorrent
    volumes:
      - ./config/radarr/config:/config
      - ./config/qbittorrent/downloads:/downloads
      - /media/apozel/hardDisk2/Movies:/movies

    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/bazarr/config:/config
      - /media/apozel/hardDisk2/Movies:/movies
      - /media/apozel/hardDisk1/Shows:/tvshows
    ports:
      - 6767:6767
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Paris
    ports:
      - 5055:5055
    volumes:
      - ./config/overseerr/config:/app/config
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - ./config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    dns: 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent/config:/config
      - ./config/qbittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
